### ISSUE TITLE
Can we make it Public?

### ISSUE THREAD

**Issue by ionut998** [reevoo/pact-support#2]
We have as dependency in a few applications and i think this is something that other people can use?

**Comment by lpil** [comment]
This is public?

**Comment by mikekr1** [comment]
Closing as per the other issue you opened.

**Comment by errm** [comment]
Can we make this private, I don't want that @lpil guy knowing what we are up to . . .

**Comment by lpil** [comment]
You seem to be making some kind of ratings and reviews app... Interesting.
